"""M3 Understanding implementation building blocks and composed IU5 engine.

The package exposes structural types, deterministic parsing, routing, model
boundaries, postprocessing, final assembly, and the composed RuntimeUnderstandingEngine.
"""

from runtime.understanding.assembly import UnderstandingStateAssembler
from runtime.understanding.catalog import (
    CandidateActionCatalog,
    IntentCatalog,
    NeedCatalog,
)
from runtime.understanding.definitions import (
    CandidateAction,
    CandidateActionDefinition,
    IntentDefinition,
    MemoryCandidate,
    NeedDefinition,
    NeedResult,
    RiskSignalSet,
    UnderstandingEvidence,
    UnderstandingEvidenceSource,
)
from runtime.understanding.deterministic import (
    ConfiguredTextRule,
    DeterministicRuleDefinition,
    DeterministicRuleFinding,
    DeterministicRuleParser,
    DeterministicUnderstandingRule,
    RuleParseResult,
    TextMatchMode,
)
from runtime.understanding.engine import RuntimeUnderstandingEngine
from runtime.understanding.errors import (
    CandidateExtractionError,
    DeterministicRuleExecutionError,
    DeterministicUnderstandingConflictError,
    DeterministicUnderstandingError,
    InvalidDeterministicRuleError,
    InvalidModelEvidenceError,
    InvalidModelUnderstandingFragmentError,
    InvalidModelUncertaintyError,
    InvalidUnderstandingCandidateError,
    InvalidUnderstandingDefinitionError,
    InvalidUnderstandingEvidenceError,
    InvalidUnderstandingRoutingPolicyError,
    MissingDeepUnderstandingResultError,
    MissingUnderstandingModelError,
    ModelBoundaryError,
    ModelInputBoundaryError,
    ModelOutputBoundaryError,
    UnderstandingAssemblyError,
    UnderstandingFoundationError,
    UnderstandingMergeConflictError,
    UnderstandingModelExecutionError,
    UnderstandingPostprocessingError,
    UnderstandingRoutingError,
)
from runtime.understanding.model_boundary import (
    DeepUnderstandingRequest,
    DeepUnderstandingRequestBuilder,
    DefaultModelContextSelector,
    ModelContextSelectionPolicy,
    ModelUnderstandingOutputValidator,
    ModelUnderstandingResult,
    SelectedModelContext,
    StructuredUnderstandingModel,
)
from runtime.understanding.postprocessing import (
    CandidateExtractionPipeline,
    CandidateExtractionResult,
    EvidenceNormalizer,
    RiskSignalNormalizer,
    UncertaintyNormalizer,
    UnderstandingCandidateExtractor,
    UnderstandingPostprocessor,
    UnderstandingPostprocessResult,
)
from runtime.understanding.routing import (
    UnderstandingPathRouter,
    UnderstandingRouteDecision,
    UnderstandingRoutingPolicy,
)

__all__ = [
    "CandidateAction",
    "CandidateActionCatalog",
    "CandidateActionDefinition",
    "CandidateExtractionError",
    "CandidateExtractionPipeline",
    "CandidateExtractionResult",
    "ConfiguredTextRule",
    "DeepUnderstandingRequest",
    "DeepUnderstandingRequestBuilder",
    "DefaultModelContextSelector",
    "DeterministicRuleDefinition",
    "DeterministicRuleExecutionError",
    "DeterministicRuleFinding",
    "DeterministicRuleParser",
    "DeterministicUnderstandingConflictError",
    "DeterministicUnderstandingError",
    "DeterministicUnderstandingRule",
    "EvidenceNormalizer",
    "IntentCatalog",
    "IntentDefinition",
    "InvalidDeterministicRuleError",
    "InvalidModelEvidenceError",
    "InvalidModelUnderstandingFragmentError",
    "InvalidModelUncertaintyError",
    "InvalidUnderstandingCandidateError",
    "InvalidUnderstandingDefinitionError",
    "InvalidUnderstandingEvidenceError",
    "InvalidUnderstandingRoutingPolicyError",
    "MemoryCandidate",
    "MissingDeepUnderstandingResultError",
    "MissingUnderstandingModelError",
    "ModelBoundaryError",
    "ModelContextSelectionPolicy",
    "ModelInputBoundaryError",
    "ModelOutputBoundaryError",
    "ModelUnderstandingOutputValidator",
    "ModelUnderstandingResult",
    "NeedCatalog",
    "NeedDefinition",
    "NeedResult",
    "RiskSignalNormalizer",
    "RiskSignalSet",
    "RuleParseResult",
    "RuntimeUnderstandingEngine",
    "SelectedModelContext",
    "StructuredUnderstandingModel",
    "TextMatchMode",
    "UncertaintyNormalizer",
    "UnderstandingAssemblyError",
    "UnderstandingCandidateExtractor",
    "UnderstandingEvidence",
    "UnderstandingEvidenceSource",
    "UnderstandingFoundationError",
    "UnderstandingMergeConflictError",
    "UnderstandingModelExecutionError",
    "UnderstandingPathRouter",
    "UnderstandingPostprocessResult",
    "UnderstandingPostprocessingError",
    "UnderstandingPostprocessor",
    "UnderstandingRouteDecision",
    "UnderstandingRoutingError",
    "UnderstandingRoutingPolicy",
    "UnderstandingStateAssembler",
]
