"""M3 Understanding implementation building blocks.

The package exposes structural foundation types, deterministic rule parsing, path
routing, a provider-neutral model boundary, and IU4 postprocessing. It still does
not provide a full UnderstandingEngine or Understanding Orchestrator.
"""

from runtime.understanding.catalog import (
    CandidateActionCatalog,
    IntentCatalog,
    NeedCatalog,
)
from runtime.understanding.definitions import (
    CandidateAction,
    CandidateActionDefinition,
    IntentDefinition,
    MemoryCandidate,
    NeedDefinition,
    NeedResult,
    RiskSignalSet,
    UnderstandingEvidence,
    UnderstandingEvidenceSource,
)
from runtime.understanding.deterministic import (
    ConfiguredTextRule,
    DeterministicRuleDefinition,
    DeterministicRuleFinding,
    DeterministicRuleParser,
    DeterministicUnderstandingRule,
    RuleParseResult,
    TextMatchMode,
)
from runtime.understanding.errors import (
    CandidateExtractionError,
    DeterministicRuleExecutionError,
    DeterministicUnderstandingConflictError,
    DeterministicUnderstandingError,
    InvalidDeterministicRuleError,
    InvalidModelEvidenceError,
    InvalidModelUncertaintyError,
    InvalidUnderstandingCandidateError,
    InvalidUnderstandingDefinitionError,
    InvalidUnderstandingEvidenceError,
    InvalidUnderstandingRoutingPolicyError,
    MissingDeepUnderstandingResultError,
    ModelBoundaryError,
    ModelInputBoundaryError,
    ModelOutputBoundaryError,
    UnderstandingFoundationError,
    UnderstandingPostprocessingError,
    UnderstandingRoutingError,
)
from runtime.understanding.model_boundary import (
    DeepUnderstandingRequest,
    DeepUnderstandingRequestBuilder,
    DefaultModelContextSelector,
    ModelContextSelectionPolicy,
    ModelUnderstandingOutputValidator,
    ModelUnderstandingResult,
    SelectedModelContext,
    StructuredUnderstandingModel,
)
from runtime.understanding.postprocessing import (
    CandidateExtractionPipeline,
    CandidateExtractionResult,
    EvidenceNormalizer,
    RiskSignalNormalizer,
    UncertaintyNormalizer,
    UnderstandingCandidateExtractor,
    UnderstandingPostprocessor,
    UnderstandingPostprocessResult,
)
from runtime.understanding.routing import (
    UnderstandingPathRouter,
    UnderstandingRouteDecision,
    UnderstandingRoutingPolicy,
)

__all__ = [
    "CandidateAction",
    "CandidateActionCatalog",
    "CandidateActionDefinition",
    "CandidateExtractionError",
    "CandidateExtractionPipeline",
    "CandidateExtractionResult",
    "ConfiguredTextRule",
    "DeepUnderstandingRequest",
    "DeepUnderstandingRequestBuilder",
    "DefaultModelContextSelector",
    "DeterministicRuleDefinition",
    "DeterministicRuleExecutionError",
    "DeterministicRuleFinding",
    "DeterministicRuleParser",
    "DeterministicUnderstandingConflictError",
    "DeterministicUnderstandingError",
    "DeterministicUnderstandingRule",
    "EvidenceNormalizer",
    "IntentCatalog",
    "IntentDefinition",
    "InvalidDeterministicRuleError",
    "InvalidModelEvidenceError",
    "InvalidModelUncertaintyError",
    "InvalidUnderstandingCandidateError",
    "InvalidUnderstandingDefinitionError",
    "InvalidUnderstandingEvidenceError",
    "InvalidUnderstandingRoutingPolicyError",
    "MemoryCandidate",
    "MissingDeepUnderstandingResultError",
    "ModelBoundaryError",
    "ModelContextSelectionPolicy",
    "ModelInputBoundaryError",
    "ModelOutputBoundaryError",
    "ModelUnderstandingOutputValidator",
    "ModelUnderstandingResult",
    "NeedCatalog",
    "NeedDefinition",
    "NeedResult",
    "RiskSignalNormalizer",
    "RiskSignalSet",
    "RuleParseResult",
    "SelectedModelContext",
    "StructuredUnderstandingModel",
    "TextMatchMode",
    "UncertaintyNormalizer",
    "UnderstandingCandidateExtractor",
    "UnderstandingEvidence",
    "UnderstandingEvidenceSource",
    "UnderstandingFoundationError",
    "UnderstandingPathRouter",
    "UnderstandingPostprocessResult",
    "UnderstandingPostprocessingError",
    "UnderstandingPostprocessor",
    "UnderstandingRouteDecision",
    "UnderstandingRoutingError",
    "UnderstandingRoutingPolicy",
]
